name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    types: [ opened, ready_for_review ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "$GITHUB_SHA"
          path: build/web
          retention-days: 7

  preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHEN2YAPP }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
